package com.miyag.howardchat;

/**
 * Created by miyag on 8/7/17.
 */

import com.google.firebase.database.DataSnapshot;

public class Message {
    private String mUserName;
    private String mUserId;
    private String mContent;

    public Message(String userName, String userId, String message) {
        mUserName = userName;
        mUserId = userId;
        mContent= message;
        // Note we do not generate a timestamp...that's only generated by the server.
    }

    public Message(DataSnapshot pingSnapshot) {
        mUserName = pingSnapshot.child("fromUserName").getValue(String.class);
        mUserId = pingSnapshot.child("fromUserId").getValue(String.class);
        mContent = pingSnapshot.child("content").getValue(String.class);
    }

    public String getUserName() {
        return mUserName;
    }

    public String getContent() {
        return mContent;
    }

    public String getUserId() {
        return mUserId;
    }
}


